apiVersion: v1
kind: Service
metadata:
  name: dailybuy-5m-service
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: dailybuy-5m
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30400
